insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Esteem', 1999, 'Turquoise', 'Suzuki');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Escort', 1987, 'Maroon', 'Ford');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Escalade', 2000, 'Yellow', 'Cadillac');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('2500 Club Coupe', 1995, 'Indigo', 'GMC');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Tacoma Xtra', 2004, 'Turquoise', 'Toyota');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('280ZX', 1979, 'Puce', 'Nissan');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Azera', 2012, 'Green', 'Hyundai');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Trans Sport', 1994, 'Red', 'Pontiac');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('RVR', 1994, 'Puce', 'Mitsubishi');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('4Runner', 2003, 'Blue', 'Toyota');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('S6', 2008, 'Indigo', 'Audi');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('LeSabre', 1998, 'Indigo', 'Buick');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('JUKE', 2011, 'Maroon', 'Nissan');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('LX', 2000, 'Puce', 'Lexus');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Corrado', 1990, 'Indigo', 'Volkswagen');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('E-Class', 1985, 'Blue', 'Mercedes-Benz');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Camaro', 1995, 'Violet', 'Chevrolet');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Range Rover Classic', 1993, 'Blue', 'Land Rover');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Century', 1990, 'Violet', 'Buick');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Ram Wagon B150', 1994, 'Crimson', 'Dodge');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Z4', 2006, 'Green', 'BMW');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('7 Series', 2012, 'Green', 'BMW');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Loyale', 1991, 'Puce', 'Subaru');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Golf', 2011, 'Violet', 'Volkswagen');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('900', 1986, 'Violet', 'Saab');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('ZX2', 2001, 'Puce', 'Ford');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Sidekick', 1998, 'Fuscia', 'Suzuki');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('80', 1989, 'Orange', 'Audi');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Corvette', 1967, 'Aquamarine', 'Chevrolet');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Navajo', 1992, 'Blue', 'Mazda');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('E350', 2009, 'Khaki', 'Ford');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('S-Class', 1986, 'Blue', 'Mercedes-Benz');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Z4 M', 2009, 'Fuscia', 'BMW');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Tempest', 1966, 'Violet', 'Pontiac');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('V70', 2005, 'Crimson', 'Volvo');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Somerset', 1986, 'Crimson', 'Buick');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('SVX', 1997, 'Turquoise', 'Subaru');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Prelude', 2000, 'Pink', 'Honda');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Mustang', 2001, 'Pink', 'Ford');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Festiva', 1988, 'Maroon', 'Ford');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Tracer', 1997, 'Turquoise', 'Mercury');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Hombre Space', 2000, 'Goldenrod', 'Isuzu');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('626', 2001, 'Goldenrod', 'Mazda');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('XL-7', 2003, 'Purple', 'Suzuki');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Grand Prix', 2000, 'Goldenrod', 'Pontiac');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('645', 2004, 'Pink', 'BMW');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('MX-6', 1992, 'Turquoise', 'Mazda');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('V70', 2007, 'Indigo', 'Volvo');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Navigator', 2001, 'Crimson', 'Lincoln');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Jetta', 1991, 'Green', 'Volkswagen');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Sportage', 2007, 'Maroon', 'Kia');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Magnum', 2005, 'Turquoise', 'Dodge');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Golf', 1992, 'Orange', 'Volkswagen');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('M5', 2010, 'Orange', 'BMW');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('xA', 2005, 'Aquamarine', 'Scion');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Tacoma Xtra', 1998, 'Goldenrod', 'Toyota');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Envoy', 2007, 'Goldenrod', 'GMC');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Solara', 2001, 'Turquoise', 'Toyota');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Volt', 2012, 'Mauv', 'Chevrolet');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Grand Cherokee', 1995, 'Puce', 'Jeep');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Ranger', 1994, 'Green', 'Ford');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('SL-Class', 1986, 'Blue', 'Mercedes-Benz');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Montana', 1999, 'Goldenrod', 'Pontiac');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Xtra', 1992, 'Yellow', 'Toyota');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('EX', 2011, 'Fuscia', 'Infiniti');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('X-90', 1998, 'Indigo', 'Suzuki');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('IS F', 2009, 'Blue', 'Lexus');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('XJ Series', 1999, 'Green', 'Jaguar');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Sedona', 2010, 'Mauv', 'Kia');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Sonoma', 2004, 'Turquoise', 'GMC');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('9-5', 2008, 'Turquoise', 'Saab');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('911', 2002, 'Red', 'Porsche');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Rodeo', 1997, 'Mauv', 'Isuzu');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Aerostar', 1991, 'Green', 'Ford');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Truck', 1991, 'Blue', 'Mitsubishi');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Sequoia', 2005, 'Maroon', 'Toyota');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Avalanche', 2006, 'Teal', 'Chevrolet');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Ramcharger', 1993, 'Pink', 'Dodge');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Celica', 1997, 'Goldenrod', 'Toyota');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('E250', 2008, 'Green', 'Ford');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Milan', 2008, 'Yellow', 'Mercury');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Escort', 1996, 'Blue', 'Ford');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('R-Class', 2007, 'Orange', 'Mercedes-Benz');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('S80', 2005, 'Green', 'Volvo');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Cabriolet', 1997, 'Turquoise', 'Audi');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Navigator', 2008, 'Violet', 'Lincoln');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Q5', 2012, 'Purple', 'Audi');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Datsun/Nissan Z-car', 1990, 'Goldenrod', 'Nissan');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('D150', 1993, 'Green', 'Dodge');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Impala', 2012, 'Orange', 'Chevrolet');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Pajero', 1989, 'Indigo', 'Mitsubishi');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Challenger', 2010, 'Maroon', 'Dodge');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Bonneville', 2001, 'Mauv', 'Pontiac');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Ram 1500', 2005, 'Red', 'Dodge');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('FX', 2010, 'Maroon', 'Infiniti');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Trooper', 1996, 'Purple', 'Isuzu');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Uplander', 2008, 'Purple', 'Chevrolet');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('E-Class', 2009, 'Teal', 'Mercedes-Benz');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('Corolla', 1998, 'Blue', 'Toyota');
insert into cars_table (car_model, car_release_Year, car_color, car_company) values ('200', 1989, 'Green', 'Audi');
